const events = {
    "mother-sewing": "Young Mother Sewing (1900) by Mary Cassatt is historically significant for its intimate portrayal of motherhood and its focus on women's domestic roles, a common theme in her work. The painting highlights Cassatt’s mastery in capturing quiet, tender moments between mother and child, emphasizing the softness and warmth of their connection. Her use of light and color to depict the everyday life of women reflects the Impressionist interest in realism and the modern world. Cassatt's work is also notable for its feminist undertones, as it elevates the private sphere of women’s lives to the level of art, countering traditional, male-dominated representations in painting.",
    "dance-class": "The Dance Class (1874-1876) by Edgar Degas is historically significant for its innovative portrayal of movement and its exploration of the working-class ballet dancers. Unlike traditional depictions of dancers in static poses, Degas captured them in action, offering a dynamic view of their practice. The painting also showcases his unique use of perspective and composition, focusing on unusual angles and the interplay of light and shadow. As a key work within the Impressionist movement, it demonstrates Degas’s interest in modern life, capturing the everyday activities of women while pushing the boundaries of classical art.",
    "water-lilies": "Monet's Water Lilies series (1897-1899) is historically significant for its exploration of color, light, and the passage of time. The series, painted in the later years of Monet's life, focuses on his water garden at Giverny, emphasizing the natural beauty and tranquility of the setting. Through loose brushstrokes and innovative use of color, Monet captures the reflections of light on the water’s surface, creating a sense of movement and fluidity. This work marks a departure from traditional landscape painting, pushing the boundaries of Impressionism and paving the way for Abstract Expressionism. It is a key example of how Monet used nature to explore perception and the transient effects of light.",
    "montmartre-night": "The Boulevard Montmartre at Night (1897) by Camille Pissarro is historically significant for its depiction of modern urban life and its exploration of light in a nocturnal setting. Pissarro captures the lively atmosphere of Paris at night, with bustling streets illuminated by gas lamps. The painting reflects the Impressionist fascination with contemporary scenes, as well as the effects of artificial light on the urban landscape. Pissarro’s loose brushwork and vibrant color palette convey the energy of the city, marking a shift from traditional landscape painting to the representation of modernity and everyday life in an evolving urban environment.",
    "moulin-galette": "Dance at Le Moulin de la Galette (1876) by Pierre-Auguste Renoir is historically significant as a quintessential example of Impressionist social realism. The painting depicts a lively, outdoor dance scene at a popular Parisian venue, showcasing Renoir’s skill in capturing movement, light, and the vibrancy of contemporary life. With its focus on the joy and energy of the moment, the work reflects the Impressionist emphasis on modernity and everyday experiences, breaking away from formal, historical subjects. It also highlights Renoir's mastery of color and brushwork, contributing to the evolution of modern art.",
    "port-marly": "Flood at Port-Marly (1876-1879) by Alfred Sisley is historically significant for its portrayal of nature's dramatic power, reflecting the Impressionist focus on atmospheric conditions and landscape. The painting depicts the devastating effects of flooding on a small town, using Sisley’s characteristic soft brushwork and subtle light to convey the transient beauty of the scene. It captures a moment of natural upheaval while focusing on the fleeting, ever-changing qualities of the environment. The work exemplifies how Impressionists sought to capture the emotional and sensory experience of nature, while moving away from traditional, idealized landscapes.",
    "the-cradle": "In 1872, The Cradle by Berthe Morisot marked a significant moment in art history as it showcased the artist's unique contribution to Impressionism. The painting depicted an intimate, domestic scene, emphasizing soft brushwork, light, and the everyday life of women, challenging traditional, more formal representations of women in art. Morisot’s use of light and focus on motherhood, a personal subject, helped solidify her role as a key figure in the Impressionist movement.",
    "snow-louveciennes": "Snow at Louveciennes (1874) by Alfred Sisley is historically significant as it exemplifies the Impressionist focus on capturing natural scenes and atmospheric effects. Painted during the movement's height, it features a winter landscape with snow, highlighting Sisley's mastery of light and color. The piece emphasizes the transient beauty of nature and the fleeting effects of weather, marking a shift from traditional, static landscapes to dynamic, momentary representations of the environment. This work further reinforced Impressionism's break from academic conventions in favor of depicting everyday scenes.",
    "rainy-day": "Paris Street, Rainy Day (1877) by Gustave Caillebotte is historically significant for its innovative approach to perspective and urban life. The painting captures a rainy day in Paris, using a unique viewpoint and precise detail to depict the bustling streets with striking realism. Caillebotte's use of a low vantage point and the reflective quality of the wet pavement emphasizes the modernity of the city, aligning with the Impressionist focus on contemporary scenes. The work also stands out for its attention to urban space, bridging traditional realism with Impressionist techniques, and helping define the evolving depiction of modern life.",
    "strolling-seashore": "Strolling along the Seashore (1909) by Joaquín Sorolla is historically significant for its vibrant depiction of light, color, and movement, characteristic of Sorolla's style. The painting showcases his mastery in capturing the effects of sunlight on the sea, sand, and figures. Sorolla’s loose, expressive brushstrokes and bright, lively palette emphasize the warmth and vitality of the scene, reflecting his ability to merge Impressionist techniques with his own unique approach. This work exemplifies Sorolla's interest in portraying the Spanish landscape and everyday life, particularly the connection between people and nature, while pushing the boundaries of color and light in a modern context.",
    "japanese-bridge": "The Japanese Bridge (1899-1900) by Claude Monet is historically significant for its exploration of East Asian influence on Western art and its focus on the interplay of light and color in nature. Painted in Monet's garden at Giverny, the bridge becomes a symbol of his fascination with Japanese aesthetics, which were popular in France at the time. Through his characteristic loose brushwork and vibrant palette, Monet captures the reflections of the bridge and surrounding foliage in the water, creating a sense of harmony and tranquility. This work is part of his broader *Water Lilies* series and reflects his ongoing exploration of perception, light, and the fleeting nature of beauty.",
    "impression-sunrise": "Impression, Sunrise by Claude Monet, painted in 1872, marked the beginning of the Impressionist movement. Its loose brushwork, focus on light, and depiction of a fleeting moment challenged traditional art norms, prioritizing subjective experience over realism. The painting's title even inspired the term, Impressionism signaling a revolutionary shift in how art was created and perceived during the late 19th century."};

function showEvent(eventId) {
    const description = document.getElementById('event-content');
    description.innerHTML = events[eventId] || "Details not available.";
}

